### PR TITLE
Add a peer dependency for react-map-gl

### PR DESCRIPTION
**Pull request by jaronheard**
Since react-map-gl-geocoder relies on react-map-gl, it should specify react-map-gl as a peer dependency.

I've picked version 3.0.0 as the minimum somewhat arbitrarily.

### CODE REVIEW

**Comment by SamSamskies** [comment]
Thanks for the PR. Let me try and see how far I can go with the version first to provide support for more users.

**Comment by SamSamskies** [comment]
Damn, minimum version of react-map-gl seems to currently be v4.0.0 to work with v.1.6.4. Did you actually try it out with v3.0.0? If you did get it working, what version of React are you using?

**Comment by SamSamskies** [comment]
Planning to merge this tonight, but I'm going to bump the react-map-gl version to 4.0.0 before publishing.

**Comment by jaronheard** [comment]
Thanks for this! Awesome 😎

We’re in the middle of a big dependency upgrade and I kind of lost track of where we were the process. I believe that it was working with the latest React 15 and latest react-map-gl 3

**Pull request merged**
