### PR TITLE
Add note to README about the pixel project matrix not invertable issue

### PR DESCRIPTION
**Pull request by yn5**
A little note in the README to address https://github.com/SamSamskies/react-map-gl-geocoder/issues/28

### CODE REVIEW

**Comment by SamSamskies** [comment]
Hi, thanks for the PR, but I'd rather fix the issue than add this to the README. It seems to be an edge case which I can't reproduce. I'll leave the issue open so people can discuss there.

**Comment by SamSamskies** [comment]
Just pushed a new version. Let me know if it fixes this issue.

**Comment by yn5** [comment]
Thanks for your support @SamSamskies ! I’ll continue working on the project using this the 29th. Will report whether it fixes the issue by then.

**Comment by yn5** [comment]
I have just tried version `2.0.4` it indeed works but throws the following warning:
```
following result caused an error when trying to zoom to bbox:
bbox: (4) [-74.2590879797556, 40.477399, -73.7008392055224, 40.917576401307]
center: (2) [-73.9808, 40.7648]
context: (2) [{…}, {…}]
geometry: {type: "Point", coordinates: Array(2)}
id: "place.15278078705964500"
language: "nl"
language_nl: "nl"
place_name: "New York, New York, Verenigde Staten van Amerika"
place_name_nl: "New York, New York, Verenigde Staten van Amerika"
place_type: ["place"]
properties: {wikidata: "Q60"}
relevance: 1
text: "New York"
text_nl: "New York"
type: "Feature"
```

Seems to happen for all search results.

Also the zoom level to which it navigates the viewport is higher than it was when using the fix proposed https://github.com/SamSamskies/react-map-gl-geocoder/issues/28

Another thing I noticed today is that the 100% height and width get immediately replaced by absolute pixel values the first time the viewport changes when using that fix. I've tried to fix that using the following handler function:
```javascript
function handleViewportChange(newViewport) {
  setViewport({
    ...newViewport,
    height: '100%',
    width: '100%',
  });
}
```
Which caused the error to be thrown again:
```
Uncaught Error: Pixel project matrix not invertible
    at WebMercatorViewport.Viewport (viewport.js:38)
    at new WebMercatorViewport (web-mercator-viewport.js:61)
    at fitBounds (index.js:118)
    at EventEmitter.Geocoder._this.handleResult (index.js:302)
    at EventEmitter.emit (events.js:136)
    at MapboxGeocoder._onChange (index.js:308)
    at Suggestions.value (suggestions.js:179)
    at List.handleMouseUp (list.js:77)
    at List.eval (list.js:71)
```
 Maybe that gives a clue?

I am using the containerRef an mapRef API's to place the Geocoder somewhere outside of the map FYI if that could possibly make any difference

**Comment by SamSamskies** [comment]
I added those warnings to help with debugging. 

It's currently zooming to default zoom level if the viewport dimensions causes an error when trying to figure out the zoom level for your result.

AFAIK, `react-map-gl` always converts the height and width to pixel values when rendering. I can dig into their source code to try and see what really happens when supplying "100%" as the value for the width and height props.

Thanks for providing your new findings. I'll dig into this more this weekend. What props are you passing to the Geocoder component? I noticed your language is set to `nl`. I wonder if that has anything to do with these issues that you're having. I have only been using the default language (at least for me) which is `en`.

**Comment by SamSamskies** [comment]
Okay, I think I've fixed the issue. I'm getting the viewport width and height from the DOM now instead of from props of the react-map-gl component. Try pulling the latest update v2.0.5.

**Comment by SamSamskies** [comment]
Closing this for now. Continue discussion in the issue if necessary. https://github.com/SamSamskies/react-map-gl-geocoder/issues/28

**Pull request closed without merging**
