### PR TITLE
Place search box to optional div id outside of map

### PR DESCRIPTION
**Pull request by vnugent**
- Introduce the ability to attach search box to an arbitrary div.  [Insipration](https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-outside-the-map/)

- Refactor initialization code to avoid null mapRef when MapGL is a child of DeckGL
```
<DeckGL ...>
  <MapGL  ref={this.mapRef}  {...other_props} >
  <Geocoder  mapRef={this.mapRef} divId="search-container"  {...other_props} />  
</DeckGL/>
```

image

### CODE REVIEW

**Comment by vnugent** [comment]
My Visual Studio Code introduces quite a major reformatting and coding style.  I'll fix that

**Comment by SamSamskies** [comment]
Current implementation works fine when MapGL is a child of DeckGL. If you've found a way to break that, could you submit an example using Code Sandbox. Otherwise, I'd like to leave the initialization code the way that it was. I already have plans to refactor the initialization code to fix issue https://github.com/SamSamskies/react-map-gl-geocoder/issues/16.

Regarding your other enhancement to place geocoder outside the map, could you close this PR and submit a separate one with just that code added and without all the styling changes? With the new PR, could you make it towards the develop branch instead of master? I'd also like to request that the prop be called containerId instead of divId.

Thanks for making the first PR! I guess I should get around to fixing issue https://github.com/SamSamskies/react-map-gl-geocoder/issues/6 (adding Prettier and ESLint) and adding a CONTRIBUTING.md doc so people don't waste their time. I'll do it over the holiday break.

**Comment by SamSamskies** [comment]
Added an issue regarding being able to place geocoder outside the map https://github.com/SamSamskies/react-map-gl-geocoder/issues/19

**Comment by SamSamskies** [comment]
I've implemented this feature in v1.6.0. I added a containerRef prop to make this possible. README has been updated.

**Pull request closed without merging**
